apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: observability
  name: prometheus-pvc-storage
  labels:
    app: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
