apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: observability
  name: pgsql-pvc-storage
  labels:
    app: pgsql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi