apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: observability
  name: grafana-pvc-storage
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
