---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volumedemo2
  namespace: workshop-ns
spec:
  selector:
    matchLabels:
      app: volumedemo2
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: volumedemo2
        tier: backend
        track: stable
    spec:
      containers:
        - name: verbose-program2
          image: node:lts-buster
          workingDir: /app
          args: ["sh", "-c", "pwd; echo ${LOGS_FOLDER}; cp -Rv /tmp/app/* ./; ls -la .; while true; do echo \"$(date)\"; sleep 1;done"]
          env:
          - name: LOGS_FOLDER
            value: /var/log/
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: node-app
              mountPath: /tmp/app
        - name: nginx
          image: nginx
          volumeMounts:
            - name: varlog
              mountPath: /var/log/program
              readOnly: true
            - name: nginx-conf
              subPath: nginx-logs.conf
              mountPath: /etc/nginx/conf.d/default.conf
      volumes:
        - name: varlog
          emptyDir: {}
        - name: node-app
          configMap:
            name: node-app-from-files
        - name: nginx-conf
          configMap:
            name: nginx-config
            items:
              - key: nginx-logs.conf
                path: nginx-logs.conf
...
---
