apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
  namespace: workshop-ns
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo2
  namespace: workshop-ns
data:
  # file-like keys
  game2.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface2.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true    
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
  namespace: workshop-ns
spec:
  containers:
    - name: demo
      image: alpine
      resources: {}
      command: ["sleep", "3600"]
      env:
        # Define the environment variable
        - name: PLAYER_INITIAL_LIVES # Notice that the case is different here
                                     # from the key name in the ConfigMap.
          valueFrom:
            configMapKeyRef:
              name: game-demo           # The ConfigMap this value comes from.
              key: player_initial_lives # The key to fetch.
        - name: UI_PROPERTIES_FILE_NAME
          valueFrom:
            configMapKeyRef:
              name: game-demo
              key: ui_properties_file_name
      volumeMounts:
        # Attach config to folder
      - name: config
        mountPath: "/config"
        readOnly: true
      - name: config2
        mountPath: "/config2"
        readOnly: false
  volumes:
    # You set volumes at the Pod level, then mount them into containers inside that Pod
    - name: config
      configMap:
        # Provide the name of the ConfigMap you want to mount.
        name: game-demo
        # An array of keys from the ConfigMap to create as files
        items:
        - key: "game.properties"
          path: "game.properties"
        - key: "user-interface.properties"
          path: "user-interface.properties"
    - name: config2
      configMap:
        # Provide the name of the ConfigMap you want to mount.
        name: game-demo2
