apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  namespace: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s # By default, scrape targets every 5 seconds.
      evaluation_interval: 15s

      # Attach these labels to any time series or alerts when communicating with
      # external systems (federation, remote storage, Alertmanager).
      external_labels:
        monitor: "minikube-test-server"

      # Load and evaluate rules in this file every 'evaluation_interval' seconds.
    rule_files:
      # - "alert.rules"
      # - "first.rules"
      # - "second.rules"

    # A scrape configuration containing exactly one endpoint to scrape:
    scrape_configs:
      # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

      - job_name: "nats-minikube-server"
        static_configs:
          - targets:
              # - "nats-service:7777"
              - "nats-service-prom-exporter0:7777"
              - "nats-service-prom-exporter1:7777"
              - "nats-service-prom-exporter2:7777"
            labels:
              namespace: "observ"
              env: "minikube"
              region: "minikube"
              service: "nats-service"

      # - job_name: "kube-staging"
      #   metrics_path: /oms-queue-exporter/metrics
      #   static_configs:
      #     - targets:
      #         - "api.staging-dlovtm.walmartdigital.cl"
      #       labels:
      #         namespace: "observ"
      #         env: "staging"
      #         region: "eastus2"
      # - job_name: "kube-staging-n0"
      #   metrics_path: /oms-queue-exporter0/metrics
      #   static_configs:
      #     - targets:
      #         - "api.staging-dlovtm.walmartdigital.cl"
      #       labels:
      #         namespace: "observ"
      #         env: "staging"
      #         region: "eastus2"
      # - job_name: "kube-staging-n1"
      #   metrics_path: /oms-queue-exporter1/metrics
      #   static_configs:
      #     - targets:
      #         - "api.staging-dlovtm.walmartdigital.cl"
      #       labels:
      #         namespace: "observ"
      #         env: "staging"
      #         region: "eastus2"
      # - job_name: "kube-staging-n2"
      #   metrics_path: /oms-queue-exporter2/metrics
      #   static_configs:
      #     - targets:
      #         - "api.staging-dlovtm.walmartdigital.cl"
      #       labels:
      #         namespace: "observ"
      #         env: "staging"
      #         region: "eastus2"

      - job_name: "oms-broker-cache-service-minikube"
        metrics_path: /metrics
        static_configs:
          - targets: ["oms-broker-cache-service:9121"]
            labels:
              namespace: "observ"
              env: "minikube"
              region: "minikube"
              service: "oms-broker-cache"
      - job_name: "oms-core-cache-service-minikube"
        metrics_path: /metrics
        static_configs:
          - targets: ["oms-core-cache-service:9121"]
            labels:
              namespace: "observ"
              env: "minikube"
              region: "minikube"
              service: "oms-core-cache"
      - job_name: "picking-core-cache-service-minikube"
        metrics_path: /metrics
        static_configs:
          - targets: ["picking-core-cache-service:9121"]
            labels:
              namespace: "observ"
              env: "minikube"
              region: "minikube"
              service: "picking-core-cache"

      - job_name: "picking-pgsql-exporter-service-minikube"
        metrics_path: /metrics
        static_configs:
          - targets: ["pgsql-exporter-service:9187"]
            labels:
              namespace: "observ"
              env: "minikube"
              region: "minikube"
              service: "picking-core-db"

      # - job_name: "redis-broker"
      #   metrics_path: /oms-broker-cache-exporter/metrics
      #   static_configs:
      #     - targets:
      #         - "api.staging-dlovtm.walmartdigital.cl"
      # - job_name: "redis-core"
      #   metrics_path: /oms-core-cache-exporter/metrics
      #   static_configs:
      #     - targets:
      #         - "api.staging-dlovtm.walmartdigital.cl"

      - job_name: prometheus-minikube-server
        static_configs:
          - targets: ["localhost:9090"]

  alert.rules: |
    groups:
    - name: example
      rules:

      # Alert for any instance that is unreachable for >2 minutes.
      - alert: service_down
        expr: up == 0
        for: 2m
        labels:
          severity: page
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minutes."

      - alert: high_load
        expr: node_load1 > 0.5
        for: 2m
        labels:
          severity: page
        annotations:
          summary: "Instance {{ $labels.instance }} under high load"
          description: "{{ $labels.instance }} of job {{ $labels.job }} is under high load."
