---
apiVersion: v1
kind: Service
metadata:
  name: volumedemo2-service-node-port-random
  namespace: workshop-ns
spec:
  selector:
    app: volumedemo2
    tier: backend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: NodePort