apiVersion: v1
data:
  prov-dash.yaml: |
    apiVersion: 1

    providers:
    - name: 'Prometheus'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /etc/grafana/provisioning/dashboards
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: grafana-conf-prov-dash
  namespace: observability
