{
 "title": "(Provisioned) Sample - NATS [statefulset] - all clusters",
 "description": "NATS Server Dashboard",
 "tags": [
  "prometheus",
  "nats",
  "staging",
  "production",
  "eastus",
  "westus",
  "queue"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "observ" },
   { "name": "service", "query": "nats-service" },
   {
    "name": "env",
    "label": "environment",
    "query": "label_values(gnatsd_varz_proto, env)"
   },
   {
    "name": "region",
    "query": "label_values(gnatsd_varz_proto, region)"
   }
  ]
 },
 "panels": [
  { "title": "OS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Max Storage",
   "type": "singlestat",
   "description": "Thresholds 600MB,750MB. Limit 1GiB",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(nss_server_bytes_total{namespace=\"$namespace\",service=\"$service\",env=\"$env\",region=\"$region\"})"
    }
   ]
  },
  {
   "title": "Max Memory",
   "type": "singlestat",
   "description": "Thresholds 256MB, 384MB with limit 512MiB",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(gnatsd_varz_mem{namespace=\"$namespace\",service=\"$service\",env=\"$env\",region=\"$region\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "Thresholds 21600s (360m/6h) [red], 259200s (4320m/72h/3d) [orange]",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(time() - process_start_time_seconds{namespace=\"$namespace\",service=\"$service\", env=\"$env\", region=\"$region\"})"
    }
   ]
  },
  {
   "title": "Server CPU by node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sort_desc(max(gnatsd_varz_cpu{namespace=\"$namespace\",service=\"$service\",env=\"$env\",region=\"$region\"}) by (server_id))",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Server Memory by node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(max(gnatsd_varz_mem{namespace=\"$namespace\",service=\"$service\",env=\"$env\",region=\"$region\"}) by (server_id))",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Uptime by node",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sort_desc(min(nss_server_info{namespace=\"$namespace\",service=\"$service\", env=\"$env\", region=\"$region\"}) by (start_time, server_id)) ",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total Messages by server",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "nss_server_msgs_total{namespace=\"$namespace\",service=\"$service\",env=\"$env\",region=\"$region\"}",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Msgs pending",
   "type": "singlestat",
   "description": "Thresholds: 300, 400 with limit 500",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nss_chan_subs_pending_count{namespace=\"$namespace\",service=\"$service\",env=\"$env\", region=\"$region\"}) / 3"
    }
   ]
  },
  {
   "title": "Msgs/Sec Pending by channel",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(nss_chan_subs_pending_count{namespace=\"$namespace\",service=\"$service\", env=\"$env\", region=\"$region\"}) by (channel) / 3)",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Msgs/Sec Pending by queue (or client group/name)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(nss_chan_subs_pending_count{namespace=\"$namespace\",service=\"$service\", env=\"$env\", region=\"$region\"}) by (queue_name) / 3)",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Bytes In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(max(gnatsd_varz_in_bytes{namespace=\"$namespace\",service=\"$service\",env=\"$env\",region=\"$region\"}) by (server_id))",
     "legendFormat": "{{server_id}}",
     "metricCategory": "0",
     "pluginId": "graph"
    }
   ]
  },
  {
   "title": "NATS Msgs In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(max(gnatsd_varz_in_msgs{namespace=\"$namespace\",service=\"$service\",env=\"$env\",region=\"$region\"}) by (server_id))",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(max(gnatsd_varz_out_bytes{namespace=\"$namespace\",service=\"$service\",env=\"$env\",region=\"$region\"}) by (server_id))",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "NATS Msgs Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(max(gnatsd_varz_out_msgs{namespace=\"$namespace\",service=\"$service\",env=\"$env\",region=\"$region\"}) by (server_id))",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  { "title": "Client Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Server Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort_desc(max(nss_server_clients{namespace=\"$namespace\",service=\"$service\",env=\"$env\",region=\"$region\"}) by (server_id))",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(max(gnatsd_varz_connections{namespace=\"$namespace\",service=\"$service\",env=\"$env\",region=\"$region\"}) by (server_id))",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Slow Consumers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(max(gnatsd_varz_slow_consumers{namespace=\"$namespace\",service=\"$service\",env=\"$env\",region=\"$region\"}) by (server_id))",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(max(gnatsd_varz_subscriptions{namespace=\"$namespace\",service=\"$service\",env=\"$env\",region=\"$region\"}) by (server_id))",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  { "title": "NATS Streaming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "NATS Streaming Channels Bytes/Sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(nss_chan_bytes_total{namespace=\"$namespace\",service=\"$service\",env=\"$env\",region=\"$region\"}[5m])) by (channel) / 3)"
    }
   ]
  },
  {
   "title": "NATS Streaming Channels Msgs/Sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(nss_chan_msgs_total{namespace=\"$namespace\",service=\"$service\",env=\"$env\",region=\"$region\"}[5m])) by (channel) / 3)"
    }
   ]
  },
  {
   "title": "NATS Streaming Server Total Bytes/Sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nss_server_bytes_total{namespace=\"$namespace\",service=\"$service\",env=\"$env\",region=\"$region\"}[5m])) by (server_id)",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "NATS Streaming Server Total Msgs/Sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(nss_server_msgs_total{namespace=\"$namespace\",service=\"$service\",env=\"$env\",region=\"$region\"}[5m])) by (server_id))",
     "legendFormat": "{{server_id}}"
    }
   ]
  }
 ]
}