{
 "title": "(Provisioned) Sample - Redis - all clusters",
 "description": "Prometheus dashboard for Redis servers",
 "tags": [
  "prometheus",
  "redis",
  "staging",
  "production",
  "eastus2",
  "westus2"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "observ" },
   { "name": "env", "label": "environment", "query": "label_values(redis_up, env)" },
   { "name": "region", "query": "label_values(redis_up, region)" },
   {
    "name": "service",
    "query": "label_values(redis_up, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{namespace=\"$namespace\",env=\"$env\",region=\"$region\",service=\"$service\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_connected_clients{namespace=\"$namespace\",env=\"$env\",region=\"$region\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes{namespace=\"$namespace\",env=\"$env\",region=\"$region\",service=\"$service\"}  / redis_memory_max_bytes{env=\"$env\",region=\"$region\",service=\"$service\"} )"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{namespace=\"$namespace\",env=\"$env\",region=\"$region\",service=\"$service\"}[1m])",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{namespace=\"$namespace\",env=\"$env\",region=\"$region\",service=\"$service\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{namespace=\"$namespace\",env=\"$env\",region=\"$region\",service=\"$service\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{namespace=\"$namespace\",env=\"$env\",region=\"$region\",service=\"$service\"}",
     "legendFormat": "used"
    },
    {
     "expr": "redis_memory_max_bytes{namespace=\"$namespace\",env=\"$env\",region=\"$region\",service=\"$service\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{namespace=\"$namespace\",env=\"$env\",region=\"$region\",service=\"$service\"}[5m])",
     "legendFormat": "{{ input }}"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{namespace=\"$namespace\",env=\"$env\",region=\"$region\",service=\"$service\"}[5m])",
     "legendFormat": "{{ output }}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=\"$namespace\",env=\"$env\",region=\"$region\",service=\"$service\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=\"$namespace\",env=\"$env\",region=\"$region\",service=\"$service\"}) - sum (redis_db_keys_expiring{env=\"$env\",region=\"$region\",service=\"$service\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{namespace=\"$namespace\",env=\"$env\",region=\"$region\",service=\"$service\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{namespace=\"$namespace\",env=\"$env\",region=\"$region\",service=\"$service\"}[5m])) by (service)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{namespace=\"$namespace\",env=\"$env\",region=\"$region\",service=\"$service\"}[5m])) by (service)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{namespace=\"$namespace\",env=\"$env\",region=\"$region\",service=\"$service\"} [1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  }
 ]
}